[project]
name = "quotes-template"
version = "0.1.0"
description = "Fill out with your own description!"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.56",
    "schedule>=1.2.2",
    "tweepy>=4.14.0",
]
