[project]
name = "audquotes"
version = "0.1.0"
description = "My personal quote bot project."
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.56",
    "schedule>=1.2.2",
    "tweepy>=4.14.0",
    "typer>=0.15.1",
]
